Add basic caching to CardSetApiClient
MisterJimson/ArtifactDeckCodeDotNet pull request #1
Opened 2018-11-15 21:51 UTC by asimonov-im

2018-11-15 22:57 UTC, asimonov-im commented
Looks like Valve [broke their API](https://github.com/ValveSoftware/ArtifactDeckCode/issues/21) (hopefully temporarily. 😭

2018-11-16 01:53 UTC, MisterJimson commented on ArtifactDeckCodeDotNet/CardSetApiClient.cs
> +                data.ExpireTimeUtc < DateTimeOffset.Now)
```suggestion
                data.ExpireTimeUtc < DateTimeOffset.UtcNow)
```

Should be UtcNow I think.

2018-11-16 02:00 UTC, MisterJimson requested changes
Awesome, thanks for the help. Looking good, just a few minor comments.

2018-11-16 02:00 UTC, MisterJimson commented on ArtifactDeckCodeDotNet.Tests/CardSetApiClientTests.cs
> +        public async void GetCardSetAsyncShouldReturnDataForSet00()
I prefer async Task to void, even in tests.

2018-11-16 02:00 UTC, MisterJimson commented on ArtifactDeckCodeDotNet/CardSetApiClient.cs
> +        internal static string DataCacheFile = Path.Combine(Path.GetTempPath(), "ArtifactSetDataCache.json");
```suggestion
        private static string DataCacheFile = Path.Combine(Path.GetTempPath(), "ArtifactSetDataCache.json");
```

2018-11-16 02:41 UTC, asimonov-im commented on ArtifactDeckCodeDotNet.Tests/CardSetApiClientTests.cs
> +        public async void GetCardSetAsyncShouldReturnDataForSet00()
Gotcha.

2018-11-16 02:45 UTC, MisterJimson approved these changes
You're the best!

2018-11-16 02:45 UTC, merged